#!/usr/bin/env python

from front.FrontEnd import FrontEnd
from player.Player import Player
from problems.Errors import CLI_Audio_Exception
from curses import wrapper

def main():
    player = Player()
    front_end = FrontEnd(player)

if __name__ == "__main__":
    main()
